intro/urls.py
from django.conf.urls import url
from . import views

app_name = 'intro'


urlpatterns = [
    url(r'^playlist', views.playlist, name='playlist'),
    url(r'^search', views.search, name='search'),
    url(r'^player', views.player, name='player'),
    url(r'^rating', views.rating, name='rating'),
    url(r'^updates', views.updates, name='updates'),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^youtube/', include('intro.urls', namespace='intro')),
]

intro/models.py
from django.db import models

# Create your models here.

intro/views.py
from django.shortcuts import render


def playlist(request):
    return render(request, 'my_uploads.html')


def search(request):
    return render(request, 'search.html')


def player(request):
    return render(request, 'youtube_player.html')


def rating(request):
    return render(request, 'rating.html')


def updates(request):
    return render(request, 'updates.html')

intro/templates/base.html
<!doctype html>
{% load static %}
<html>
  <head>
    <title>YouTube</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/env.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/auth.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/search.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/my_uploads.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </head>
  <body>
    <section class="hero is-dark">
      <div class="hero-body">
        <div class="container">
          <h1 class="title">
            For YouTube
          </h1>
          {% block title %}
          {% endblock %}
        </div>
      </div>
    </section>
    <div class="container" style="margin-top: 50px;">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

intro/templates/foo.html
<!doctype html>
{% load static %}
<html>
  <head>
    <title>Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/env.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/auth.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/search.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </head>
  <body>
  <section class="hero is-dark">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          For YouTube
        </h1>
        <h2 class="subtitle">
          <label>
            <input id="query" value="Coxon Kang" type="text"/>
            <button id="search-button" disabled onclick="search()">Search</button>
          </label>
        </h2>
      </div>
    </div>
  </section>
    <div class="container" style="margin-top: 50px;">
      <div id="search-container">
    </div>
  </body>
</html>



<!---->


<!doctype html>
{% load static %}
<html>
  <head>
    <title>My Uploads</title>
    <link rel="stylesheet" type="text/css" href="{% static 'intro/my_uploads.css' %}"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/env.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/auth.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/my_uploads.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </head>
  <body>

    <div id="login-container" class="pre-auth">
      This application requires access to your YouTube account.
      Please <a href="#" id="login-link">authorize</a> to continue.
    </div>

    <div id="video-container">
        <!--<iframe class="video w100" width="640" height="360" src="//www.youtube.com/embed/"+{{ videoId }} frameborder="0" allowfullscreen></iframe>-->
    </div>

    <div class="button-container">
      <button id="prev-button" class="paging-button" onclick="previousPage();">Previous Page</button>
      <button id="next-button" class="paging-button" onclick="nextPage();">Next Page</button>
    </div>
  </body>
</html>

intro/templates/my_uploads.html
{% extends 'base.html' %}

{% block title %}
<h2 class="subtitle">
    <a href="{% url 'intro:search' %}">검색어 입력하기</a> | <strong>좋아요 목록</strong>
</h2>
<div class="button-container">
  <button id="prev-button" class="paging-button" onclick="previousPage();">Previous Page</button>
  <button id="next-button" class="paging-button" onclick="nextPage();">Next Page</button>
</div>
{% endblock %}

{% block content %}

<div id="login-container" class="pre-auth">
  This application requires access to your YouTube account.
  Please <a href="#" id="login-link">authorize</a> to continue.
</div>

<div id="video-container">
    <!--<iframe class="video w100" width="640" height="360" src="//www.youtube.com/embed/"+{{ videoId }} frameborder="0" allowfullscreen></iframe>-->
</div>
{% endblock %}

intro/templates/rating.html
<!doctype html>
{% load static %}
<html>
  <head>
    <title>Rating</title>
    <link rel="stylesheet" type="text/css" href="{% static 'intro/my_uploads.css' %}"/>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/env.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/auth.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/rating.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </head>
  <body>

    <div id="login-container" class="pre-auth">
      This application requires access to your YouTube account.
      Please <a href="#" id="login-link">authorize</a> to continue.
    </div>

    <div id="video-container">
        <!--<iframe class="video w100" width="640" height="360" src="//www.youtube.com/embed/"+{{ videoId }} frameborder="0" allowfullscreen></iframe>-->
    </div>

    <div class="button-container">
      <button id="prev-button" class="paging-button" onclick="previousPage();">Previous Page</button>
      <button id="next-button" class="paging-button" onclick="nextPage();">Next Page</button>
    </div>
  </body>
</html>

intro/templates/search.html
{% extends 'base.html' %}

{% block title %}
<h2 class="subtitle">
  <strong>검색어 입력하기</strong> | <a href="{% url 'intro:playlist' %}">좋아요 목록</a>
</h2>
<label>
  <input id="query" value="Coxon Kang" type="text"/>
  <button id="search-button" onclick="search()">Search</button>
</label>
{% endblock %}

{% block content %}
<div id="search-container">
{% endblock %}

intro/templates/updates.html
<!doctype html>
{% load static %}
<html>
  <head>
    <title>Playlist Updates</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/env.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/auth.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/updates.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </head>
  <body>
    <div id="login-container" class="pre-auth">This application requires access to your YouTube account.
      Please <a href="#" id="login-link">authorize</a> to continue.
    </div>
    <div id="buttons">
      <button id="playlist-button" disabled onclick="createPlaylist()">Create a new Private Playlist</button>
      <br>
      <label>Current Playlist Id: <input id="playlist-id" value='' type="text"/></label>
      <br>
      <label>Video Id: <input id="video-id" value='GZG9G5txtaE' type="text"/></label><button onclick="addVideoToPlaylist()">Add to current playlist</button>
    </div>
    <h3>Playlist: <span id="playlist-title"></span></h3>
    <p id="playlist-description"></p>
    <div id="playlist-container">
      <span id="status">No Videos</span>
    </div>
  </body>
</html>

intro/templates/youtube_player.html
<!doctype html>
{% load static %}
<html>
  <head>
    <title>Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
  </head>
  <body>
    <div id="youTubePlayer1"></div><!-- 플레이어를 불러올 영역-->

    <div class="button is-success is-rounded">
        <div class="btn_play">시작</div><!-- 시작버튼-->
    </div>

    <div class="button is-danger is-rounded">
        <div class="btn_stop">정지</div><!-- 정지버튼-->
    </div>

    <div class="button is-warning is-rounded">
        <div class="btn_pause">일시정지</div> <!-- 일시정지버튼-->
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'js/youtube_player.js' %}" type="text/javascript"></script>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>
  </body>
</html>